<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122164729 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agencies (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(10) NOT NULL, nom VARCHAR(100) NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_list_id INT DEFAULT NULL, kizeo_external_list_id INT DEFAULT NULL, is_active TINYINT NOT NULL, adresse VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, ville VARCHAR(100) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, UNIQUE INDEX UNIQ_F65A4DC477153098 (code), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s10 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s100 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s120 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s130 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s140 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s150 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s160 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s170 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s40 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s50 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s60 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s70 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contact_s80 (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, rib VARCHAR(255) DEFAULT NULL, contact_site VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contacts_cc (id INT AUTO_INCREMENT NOT NULL, id_contact VARCHAR(255) NOT NULL, raison_sociale_contact VARCHAR(255) NOT NULL, code_agence VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s10 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_AFB67E65E7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s100 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_C9ACFC88E7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s120 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_FB9A9E0AE7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s130 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_E281AF4BE7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s140 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_ADC0398CE7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s150 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_B4DB08CDE7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s160 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_9FF65B0EE7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s170 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature DATE NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation DATE DEFAULT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_86ED6A4FE7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s40 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_D2C18A20E7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s50 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_CBDABB61E7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s60 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_E0F7E8A2E7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s70 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_F9ECD9E3E7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrat_s80 (id INT AUTO_INCREMENT NOT NULL, numero_contrat INT NOT NULL, date_signature VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, tacite_reconduction TINYINT NOT NULL, valorisation VARCHAR(255) NOT NULL, nombre_equipement INT NOT NULL, nombre_visite INT NOT NULL, date_resiliation VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_previsionnelle_1 VARCHAR(255) DEFAULT NULL, date_previsionnelle_2 VARCHAR(255) DEFAULT NULL, date_effective_1 VARCHAR(255) DEFAULT NULL, date_effective_2 VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) DEFAULT NULL, contact_id INT DEFAULT NULL, INDEX IDX_7E74C52CE7A1254A (contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE contrats_cadre (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) NOT NULL, slug VARCHAR(50) NOT NULL, search_pattern VARCHAR(100) NOT NULL, logo VARCHAR(255) DEFAULT NULL, primary_color VARCHAR(7) DEFAULT NULL, is_active TINYINT NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_4FD1D21989D9B62 (slug), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s10 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s10_contact (id_contact), INDEX idx_s10_visite (visite), INDEX idx_s10_annee (annee), INDEX idx_s10_lookup (id_contact, visite, annee), INDEX idx_s10_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s100 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s100_contact (id_contact), INDEX idx_s100_visite (visite), INDEX idx_s100_annee (annee), INDEX idx_s100_lookup (id_contact, visite, annee), INDEX idx_s100_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s120 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s120_contact (id_contact), INDEX idx_s120_visite (visite), INDEX idx_s120_annee (annee), INDEX idx_s120_lookup (id_contact, visite, annee), INDEX idx_s120_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s130 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s130_contact (id_contact), INDEX idx_s130_visite (visite), INDEX idx_s130_annee (annee), INDEX idx_s130_lookup (id_contact, visite, annee), INDEX idx_s130_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s140 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s140_contact (id_contact), INDEX idx_s140_visite (visite), INDEX idx_s140_annee (annee), INDEX idx_s140_lookup (id_contact, visite, annee), INDEX idx_s140_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s150 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s150_contact (id_contact), INDEX idx_s150_visite (visite), INDEX idx_s150_annee (annee), INDEX idx_s150_lookup (id_contact, visite, annee), INDEX idx_s150_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s160 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s160_contact (id_contact), INDEX idx_s160_visite (visite), INDEX idx_s160_annee (annee), INDEX idx_s160_lookup (id_contact, visite, annee), INDEX idx_s160_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s170 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s170_contact (id_contact), INDEX idx_s170_visite (visite), INDEX idx_s170_annee (annee), INDEX idx_s170_lookup (id_contact, visite, annee), INDEX idx_s170_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s40 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s40_contact (id_contact), INDEX idx_s40_visite (visite), INDEX idx_s40_annee (annee), INDEX idx_s40_lookup (id_contact, visite, annee), INDEX idx_s40_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s50 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s50_contact (id_contact), INDEX idx_s50_visite (visite), INDEX idx_s50_annee (annee), INDEX idx_s50_lookup (id_contact, visite, annee), INDEX idx_s50_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s60 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s60_contact (id_contact), INDEX idx_s60_visite (visite), INDEX idx_s60_annee (annee), INDEX idx_s60_lookup (id_contact, visite, annee), INDEX idx_s60_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s70 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s70_contact (id_contact), INDEX idx_s70_visite (visite), INDEX idx_s70_annee (annee), INDEX idx_s70_lookup (id_contact, visite, annee), INDEX idx_s70_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE equipement_s80 (id INT AUTO_INCREMENT NOT NULL, id_contact INT NOT NULL, numero_equipement VARCHAR(50) NOT NULL, libelle_equipement VARCHAR(255) NOT NULL, visite VARCHAR(5) NOT NULL, annee VARCHAR(4) DEFAULT NULL, date_derniere_visite DATE DEFAULT NULL, repere_site_client VARCHAR(255) DEFAULT NULL, mise_en_service VARCHAR(10) DEFAULT NULL, numero_serie VARCHAR(100) DEFAULT NULL, marque VARCHAR(100) DEFAULT NULL, mode_fonctionnement VARCHAR(50) DEFAULT NULL, hauteur VARCHAR(20) DEFAULT NULL, largeur VARCHAR(20) DEFAULT NULL, longueur VARCHAR(20) DEFAULT NULL, etat_equipement LONGTEXT DEFAULT NULL, statut_equipement VARCHAR(5) DEFAULT NULL, anomalies LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, trigramme_tech VARCHAR(10) DEFAULT NULL, signature_tech LONGTEXT DEFAULT NULL, is_hors_contrat TINYINT NOT NULL, is_archive TINYINT NOT NULL, kizeo_form_id INT DEFAULT NULL, kizeo_data_id INT DEFAULT NULL, kizeo_index INT DEFAULT NULL, date_enregistrement DATETIME NOT NULL, date_modification DATETIME DEFAULT NULL, INDEX idx_s80_contact (id_contact), INDEX idx_s80_visite (visite), INDEX idx_s80_annee (annee), INDEX idx_s80_lookup (id_contact, visite, annee), INDEX idx_s80_kizeo_dedup (kizeo_form_id, kizeo_data_id, kizeo_index), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE files_cc (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, id_contact_cc_id INT NOT NULL, INDEX IDX_C76D26063B217F25 (id_contact_cc_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE photos (id INT AUTO_INCREMENT NOT NULL, photo_plaque VARCHAR(255) DEFAULT NULL, photo_choc VARCHAR(255) DEFAULT NULL, photo_choc_montant VARCHAR(255) DEFAULT NULL, photo_panneau_intermediaire_i VARCHAR(255) DEFAULT NULL, photo_panneau_bas_inter_ext VARCHAR(255) DEFAULT NULL, photo_lame_basse__int_ext VARCHAR(255) DEFAULT NULL, photo_lame_intermediaire_int_ VARCHAR(255) DEFAULT NULL, photo_envirronement_eclairage VARCHAR(255) DEFAULT NULL, photo_bache VARCHAR(255) DEFAULT NULL, photo_marquage_au_sol VARCHAR(255) DEFAULT NULL, photo_environnement_equipement1 VARCHAR(255) DEFAULT NULL, photo_coffret_de_commande VARCHAR(255) DEFAULT NULL, photo_carte VARCHAR(255) DEFAULT NULL, photo_rail VARCHAR(255) DEFAULT NULL, photo_equerre_rail VARCHAR(255) DEFAULT NULL, photo_fixation_coulisse VARCHAR(255) DEFAULT NULL, photo_moteur VARCHAR(255) DEFAULT NULL, photo_deformation_plateau VARCHAR(255) DEFAULT NULL, photo_deformation_plaque VARCHAR(255) DEFAULT NULL, photo_deformation_structure VARCHAR(255) DEFAULT NULL, photo_deformation_chassis VARCHAR(255) DEFAULT NULL, photo_deformation_levre VARCHAR(255) DEFAULT NULL, photo_fissure_cordon VARCHAR(255) DEFAULT NULL, photo_joue VARCHAR(255) DEFAULT NULL, photo_butoir VARCHAR(255) DEFAULT NULL, photo_vantail VARCHAR(255) DEFAULT NULL, photo_linteau VARCHAR(255) DEFAULT NULL, photo_barriere VARCHAR(255) DEFAULT NULL, photo_tourniquet VARCHAR(255) DEFAULT NULL, photo_sas VARCHAR(255) DEFAULT NULL, photo_marquage_au_sol_ VARCHAR(255) DEFAULT NULL, photo_marquage_au_sol_2 VARCHAR(255) DEFAULT NULL, photo_2 VARCHAR(255) DEFAULT NULL, form_id VARCHAR(255) DEFAULT NULL, data_id VARCHAR(255) DEFAULT NULL, equipment_id VARCHAR(255) DEFAULT NULL, update_time VARCHAR(255) DEFAULT NULL, code_equipement VARCHAR(255) DEFAULT NULL, raison_sociale_visite VARCHAR(255) DEFAULT NULL, photo_etiquette_somafi VARCHAR(255) DEFAULT NULL, photo_choc_tablier_porte VARCHAR(255) DEFAULT NULL, photo_choc_tablier VARCHAR(255) DEFAULT NULL, photo_axe VARCHAR(255) DEFAULT NULL, photo_serrure VARCHAR(255) DEFAULT NULL, photo_serrure1 VARCHAR(255) DEFAULT NULL, photo_feux VARCHAR(255) DEFAULT NULL, photo_compte_rendu VARCHAR(255) DEFAULT NULL, id_contact VARCHAR(255) NOT NULL, id_societe VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s10 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_5569176F422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s100 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_2983CAFF422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s120 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_1BB5A87D422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s130 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_2AE993C422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s140 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_4DEF0FFB422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s150 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_54F43EBA422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s160 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_7FD96D79422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s170 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_66C25C38422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s40 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_281EE32A422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s50 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_3105D26B422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s60 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_1A2881A8422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s70 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_333B0E9422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE mail_s80 (id INT AUTO_INCREMENT NOT NULL, pdf_filename VARCHAR(255) NOT NULL, sent_at DATETIME NOT NULL, pdf_url VARCHAR(255) NOT NULL, is_pdf_sent TINYINT NOT NULL, sender VARCHAR(255) NOT NULL, id_contact_id INT NOT NULL, INDEX IDX_84ABAC26422BA59D (id_contact_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE short_links (id INT AUTO_INCREMENT NOT NULL, short_code VARCHAR(10) NOT NULL, original_url VARCHAR(255) NOT NULL, agence VARCHAR(50) NOT NULL, client_id VARCHAR(50) NOT NULL, annee VARCHAR(4) NOT NULL, visite VARCHAR(50) NOT NULL, created_at DATETIME NOT NULL, expires_at DATETIME DEFAULT NULL, click_count INT DEFAULT 0 NOT NULL, last_accessed_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_5187011D17D2FE0D (short_code), INDEX idx_short_code (short_code), INDEX idx_expires_at (expires_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s10 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) DEFAULT NULL, adressep_1 VARCHAR(255) DEFAULT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) DEFAULT NULL, villep VARCHAR(255) DEFAULT NULL, siret VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s100 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s120 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s130 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s140 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s150 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s160 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s170 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s40 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s50 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s60 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s70 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE societe_s80 (id INT AUTO_INCREMENT NOT NULL, raison_sociale VARCHAR(255) NOT NULL, adressep_1 VARCHAR(255) NOT NULL, adressep_2 VARCHAR(255) DEFAULT NULL, cpostalp VARCHAR(255) NOT NULL, villep VARCHAR(255) NOT NULL, siret VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, id_societe VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, is_active TINYINT NOT NULL, agencies JSON DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, last_login_at DATETIME DEFAULT NULL, contrat_cadre_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E92AC7C0CA (contrat_cadre_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE contrat_s10 ADD CONSTRAINT FK_AFB67E65E7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s10 (id)');
        $this->addSql('ALTER TABLE contrat_s100 ADD CONSTRAINT FK_C9ACFC88E7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s100 (id)');
        $this->addSql('ALTER TABLE contrat_s120 ADD CONSTRAINT FK_FB9A9E0AE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s120 (id)');
        $this->addSql('ALTER TABLE contrat_s130 ADD CONSTRAINT FK_E281AF4BE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s130 (id)');
        $this->addSql('ALTER TABLE contrat_s140 ADD CONSTRAINT FK_ADC0398CE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s140 (id)');
        $this->addSql('ALTER TABLE contrat_s150 ADD CONSTRAINT FK_B4DB08CDE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s150 (id)');
        $this->addSql('ALTER TABLE contrat_s160 ADD CONSTRAINT FK_9FF65B0EE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s160 (id)');
        $this->addSql('ALTER TABLE contrat_s170 ADD CONSTRAINT FK_86ED6A4FE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s170 (id)');
        $this->addSql('ALTER TABLE contrat_s40 ADD CONSTRAINT FK_D2C18A20E7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s40 (id)');
        $this->addSql('ALTER TABLE contrat_s50 ADD CONSTRAINT FK_CBDABB61E7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s50 (id)');
        $this->addSql('ALTER TABLE contrat_s60 ADD CONSTRAINT FK_E0F7E8A2E7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s60 (id)');
        $this->addSql('ALTER TABLE contrat_s70 ADD CONSTRAINT FK_F9ECD9E3E7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s70 (id)');
        $this->addSql('ALTER TABLE contrat_s80 ADD CONSTRAINT FK_7E74C52CE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_s80 (id)');
        $this->addSql('ALTER TABLE files_cc ADD CONSTRAINT FK_C76D26063B217F25 FOREIGN KEY (id_contact_cc_id) REFERENCES contacts_cc (id)');
        $this->addSql('ALTER TABLE mail_s10 ADD CONSTRAINT FK_5569176F422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s10 (id)');
        $this->addSql('ALTER TABLE mail_s100 ADD CONSTRAINT FK_2983CAFF422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s100 (id)');
        $this->addSql('ALTER TABLE mail_s120 ADD CONSTRAINT FK_1BB5A87D422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s120 (id)');
        $this->addSql('ALTER TABLE mail_s130 ADD CONSTRAINT FK_2AE993C422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s130 (id)');
        $this->addSql('ALTER TABLE mail_s140 ADD CONSTRAINT FK_4DEF0FFB422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s140 (id)');
        $this->addSql('ALTER TABLE mail_s150 ADD CONSTRAINT FK_54F43EBA422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s150 (id)');
        $this->addSql('ALTER TABLE mail_s160 ADD CONSTRAINT FK_7FD96D79422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s160 (id)');
        $this->addSql('ALTER TABLE mail_s170 ADD CONSTRAINT FK_66C25C38422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s170 (id)');
        $this->addSql('ALTER TABLE mail_s40 ADD CONSTRAINT FK_281EE32A422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s40 (id)');
        $this->addSql('ALTER TABLE mail_s50 ADD CONSTRAINT FK_3105D26B422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s50 (id)');
        $this->addSql('ALTER TABLE mail_s60 ADD CONSTRAINT FK_1A2881A8422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s60 (id)');
        $this->addSql('ALTER TABLE mail_s70 ADD CONSTRAINT FK_333B0E9422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s70 (id)');
        $this->addSql('ALTER TABLE mail_s80 ADD CONSTRAINT FK_84ABAC26422BA59D FOREIGN KEY (id_contact_id) REFERENCES contact_s80 (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E92AC7C0CA FOREIGN KEY (contrat_cadre_id) REFERENCES contrats_cadre (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contrat_s10 DROP FOREIGN KEY FK_AFB67E65E7A1254A');
        $this->addSql('ALTER TABLE contrat_s100 DROP FOREIGN KEY FK_C9ACFC88E7A1254A');
        $this->addSql('ALTER TABLE contrat_s120 DROP FOREIGN KEY FK_FB9A9E0AE7A1254A');
        $this->addSql('ALTER TABLE contrat_s130 DROP FOREIGN KEY FK_E281AF4BE7A1254A');
        $this->addSql('ALTER TABLE contrat_s140 DROP FOREIGN KEY FK_ADC0398CE7A1254A');
        $this->addSql('ALTER TABLE contrat_s150 DROP FOREIGN KEY FK_B4DB08CDE7A1254A');
        $this->addSql('ALTER TABLE contrat_s160 DROP FOREIGN KEY FK_9FF65B0EE7A1254A');
        $this->addSql('ALTER TABLE contrat_s170 DROP FOREIGN KEY FK_86ED6A4FE7A1254A');
        $this->addSql('ALTER TABLE contrat_s40 DROP FOREIGN KEY FK_D2C18A20E7A1254A');
        $this->addSql('ALTER TABLE contrat_s50 DROP FOREIGN KEY FK_CBDABB61E7A1254A');
        $this->addSql('ALTER TABLE contrat_s60 DROP FOREIGN KEY FK_E0F7E8A2E7A1254A');
        $this->addSql('ALTER TABLE contrat_s70 DROP FOREIGN KEY FK_F9ECD9E3E7A1254A');
        $this->addSql('ALTER TABLE contrat_s80 DROP FOREIGN KEY FK_7E74C52CE7A1254A');
        $this->addSql('ALTER TABLE files_cc DROP FOREIGN KEY FK_C76D26063B217F25');
        $this->addSql('ALTER TABLE mail_s10 DROP FOREIGN KEY FK_5569176F422BA59D');
        $this->addSql('ALTER TABLE mail_s100 DROP FOREIGN KEY FK_2983CAFF422BA59D');
        $this->addSql('ALTER TABLE mail_s120 DROP FOREIGN KEY FK_1BB5A87D422BA59D');
        $this->addSql('ALTER TABLE mail_s130 DROP FOREIGN KEY FK_2AE993C422BA59D');
        $this->addSql('ALTER TABLE mail_s140 DROP FOREIGN KEY FK_4DEF0FFB422BA59D');
        $this->addSql('ALTER TABLE mail_s150 DROP FOREIGN KEY FK_54F43EBA422BA59D');
        $this->addSql('ALTER TABLE mail_s160 DROP FOREIGN KEY FK_7FD96D79422BA59D');
        $this->addSql('ALTER TABLE mail_s170 DROP FOREIGN KEY FK_66C25C38422BA59D');
        $this->addSql('ALTER TABLE mail_s40 DROP FOREIGN KEY FK_281EE32A422BA59D');
        $this->addSql('ALTER TABLE mail_s50 DROP FOREIGN KEY FK_3105D26B422BA59D');
        $this->addSql('ALTER TABLE mail_s60 DROP FOREIGN KEY FK_1A2881A8422BA59D');
        $this->addSql('ALTER TABLE mail_s70 DROP FOREIGN KEY FK_333B0E9422BA59D');
        $this->addSql('ALTER TABLE mail_s80 DROP FOREIGN KEY FK_84ABAC26422BA59D');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E92AC7C0CA');
        $this->addSql('DROP TABLE agencies');
        $this->addSql('DROP TABLE contact_s10');
        $this->addSql('DROP TABLE contact_s100');
        $this->addSql('DROP TABLE contact_s120');
        $this->addSql('DROP TABLE contact_s130');
        $this->addSql('DROP TABLE contact_s140');
        $this->addSql('DROP TABLE contact_s150');
        $this->addSql('DROP TABLE contact_s160');
        $this->addSql('DROP TABLE contact_s170');
        $this->addSql('DROP TABLE contact_s40');
        $this->addSql('DROP TABLE contact_s50');
        $this->addSql('DROP TABLE contact_s60');
        $this->addSql('DROP TABLE contact_s70');
        $this->addSql('DROP TABLE contact_s80');
        $this->addSql('DROP TABLE contacts_cc');
        $this->addSql('DROP TABLE contrat_s10');
        $this->addSql('DROP TABLE contrat_s100');
        $this->addSql('DROP TABLE contrat_s120');
        $this->addSql('DROP TABLE contrat_s130');
        $this->addSql('DROP TABLE contrat_s140');
        $this->addSql('DROP TABLE contrat_s150');
        $this->addSql('DROP TABLE contrat_s160');
        $this->addSql('DROP TABLE contrat_s170');
        $this->addSql('DROP TABLE contrat_s40');
        $this->addSql('DROP TABLE contrat_s50');
        $this->addSql('DROP TABLE contrat_s60');
        $this->addSql('DROP TABLE contrat_s70');
        $this->addSql('DROP TABLE contrat_s80');
        $this->addSql('DROP TABLE contrats_cadre');
        $this->addSql('DROP TABLE equipement_s10');
        $this->addSql('DROP TABLE equipement_s100');
        $this->addSql('DROP TABLE equipement_s120');
        $this->addSql('DROP TABLE equipement_s130');
        $this->addSql('DROP TABLE equipement_s140');
        $this->addSql('DROP TABLE equipement_s150');
        $this->addSql('DROP TABLE equipement_s160');
        $this->addSql('DROP TABLE equipement_s170');
        $this->addSql('DROP TABLE equipement_s40');
        $this->addSql('DROP TABLE equipement_s50');
        $this->addSql('DROP TABLE equipement_s60');
        $this->addSql('DROP TABLE equipement_s70');
        $this->addSql('DROP TABLE equipement_s80');
        $this->addSql('DROP TABLE files_cc');
        $this->addSql('DROP TABLE photos');
        $this->addSql('DROP TABLE mail_s10');
        $this->addSql('DROP TABLE mail_s100');
        $this->addSql('DROP TABLE mail_s120');
        $this->addSql('DROP TABLE mail_s130');
        $this->addSql('DROP TABLE mail_s140');
        $this->addSql('DROP TABLE mail_s150');
        $this->addSql('DROP TABLE mail_s160');
        $this->addSql('DROP TABLE mail_s170');
        $this->addSql('DROP TABLE mail_s40');
        $this->addSql('DROP TABLE mail_s50');
        $this->addSql('DROP TABLE mail_s60');
        $this->addSql('DROP TABLE mail_s70');
        $this->addSql('DROP TABLE mail_s80');
        $this->addSql('DROP TABLE short_links');
        $this->addSql('DROP TABLE societe_s10');
        $this->addSql('DROP TABLE societe_s100');
        $this->addSql('DROP TABLE societe_s120');
        $this->addSql('DROP TABLE societe_s130');
        $this->addSql('DROP TABLE societe_s140');
        $this->addSql('DROP TABLE societe_s150');
        $this->addSql('DROP TABLE societe_s160');
        $this->addSql('DROP TABLE societe_s170');
        $this->addSql('DROP TABLE societe_s40');
        $this->addSql('DROP TABLE societe_s50');
        $this->addSql('DROP TABLE societe_s60');
        $this->addSql('DROP TABLE societe_s70');
        $this->addSql('DROP TABLE societe_s80');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
